import { Geist, Geist_Mono } from "next/font/google";
import "../../../app/globals.css";
import SideNav from "@/app/components/DashBoard/common/SideNav";
import TopNav from "@/app/components/DashBoard/common/TopNav";
import Footer from "@/app/components/DashBoard/common/Footer";
import { ThemeProvider } from "@/app/context/ThemeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  //   const token = await cookies();
  //   const myToken = token.get("token")?.value;

  //   if (!myToken) {
  //     return redirect("/login");
  //   }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full  flex bg-[#e5e5ea] dark:bg-slate-800 transition-colors duration-300`}
      >
        <ThemeProvider>
          <SideNav />

          <div className="">
            <TopNav />
            <div className="lg:mt-28 mt-36  px-4">{children}</div>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
